### ISSUE TITLE
png.ProtocolError

### ISSUE THREAD

**Issue by openable** [mushfiqulalam/isp#1]
I got the error message below. My 3 PCs (Windows, Ubuntu, Mac) occurred the same message. Only 1 Redhat server didn't show the message. All of them were python 3.5. I don't know what there is any difference of environment.

===

(py3.5) my_mac:isp $ python main.py 
----------------------------------------------------
Running black level correction...
----------------------------------------------------
Running lens shading correction with flat field compensation...
----------------------------------------------------
Running bad pixel correction...
bad pixel correction: Quarter 1 of 4
bad pixel correction: Quarter 2 of 4
bad pixel correction: Quarter 3 of 4
bad pixel correction: Quarter 4 of 4
----------------------------------------------------
Running channel gain white balance...
----------------------------------------------------
Running demosaicing using directionally weighted gradient based interpolation...
Traceback (most recent call last):
  File "main.py", line 292, in <module>
    utility.imsave(data, "images/" + image_name + "_out_demosaic.png", "uint16")
  File "/Users/openable_MBP/Dropbox/Dev/isp/utility.py", line 101, in imsave
    writer.write(f, data2list)
  File "/Users/openable_MBP/anaconda3/envs/py3.5/lib/python3.5/site-packages/png.py", line 670, in write
    nrows = self.write_passes(outfile, check_rows(rows))
  File "/Users/openable_MBP/anaconda3/envs/py3.5/lib/python3.5/site-packages/png.py", line 704, in write_passes
    return self.write_packed(outfile, rows)
  File "/Users/openable_MBP/anaconda3/envs/py3.5/lib/python3.5/site-packages/png.py", line 736, in write_packed
    for i, row in enumerate(rows):
  File "/Users/openable_MBP/anaconda3/envs/py3.5/lib/python3.5/site-packages/png.py", line 992, in unpack_rows
    for row in rows:
  File "/Users/openable_MBP/anaconda3/envs/py3.5/lib/python3.5/site-packages/png.py", line 662, in check_rows
    (vpr, len(row), i))
png.ProtocolError: ProtocolError: Expected 768 values but got 2304 value, in row 0
(py3.5) my_mac:isp $ ls images/
DSC_1320_2048x2048_rggb.raw
DSC_1339.raw
DSC_1339_768x512_bggr.raw
DSC_1339_768x512_gbrg.raw
DSC_1339_768x512_grbg.raw
DSC_1339_768x512_rggb.raw
DSC_1339_768x512_rggb_bpc_test.raw
DSC_1339_768x512_rggb_dark_current_image.png
DSC_1339_768x512_rggb_flat_field_image.png
DSC_1339_768x512_rggb_out_bad_pixel_correction.png
DSC_1339_768x512_rggb_out_black_level_correction.png
DSC_1339_768x512_rggb_out_channel_gain_white_balance.png
DSC_1339_768x512_rggb_out_demosaic.png
DSC_1339_768x512_rggb_out_lens_shading_correction.png
DSC_1372_6032x4032_rggb.raw
===

**Comment by Kiyamou** [comment]
Please check the version of `png` (pypng). The pypng 0.0.18 is suitable.

Check version
```
pip list
```

Install
```
pip install pypng==0.0.18
```
